### ISSUE TITLE
Remove gitlab host

### ISSUE THREAD

**Issue by juref** [JennieJi/vsext-gitlab-snippets#4]
How to remove GitLab host? Where are hosts written?

Thank you!

**Comment by JennieJi** [comment]
Hi @juref , do you mean after you add the gitlab host in vscode would like to find a way to remove it?

**Comment by juref** [comment]
Yes, I have added a host witch I am not using anymore. It is from a former employer. Thx!

**Comment by JennieJi** [comment]
Undertand, currently the functionality is there but not exposed to user. Are you interested in contributing a PR?

**Comment by juref** [comment]
Yes, I am, but I would need some help since I am new to PR and hactoberfest.

**Comment by JennieJi** [comment]
Sure I can help. 

Since this is new feature, so I'd like to suggest 2 possible options:
1. Add a `remove host` command in vscode [command platette](https://code.visualstudio.com/api/extension-guides/command), and just list out all the available ones for selection and remove
2. In the snippet [tree view](https://code.visualstudio.com/api/extension-guides/tree-view), there's a `explore snippets` panel, and the root level is the list of added hosts, may consider add a `x` button on the right to trigger the removal

**Comment by juref** [comment]
Hi Jennie,

I'm sorry but I think this is just too much for me. I was able to get the "remove host" command to vscode command palette and I think I was able to select a host to delete, but I don't have enough knowledge to delete a host from listManager.

**Comment by JennieJi** [comment]
@juref got it no worries, if you have anything already, can give me a PR and I'll finish the rest :)

**Comment by JennieJi** [comment]
@juref just published new version. If after upgrade your side still got problem pls let me know.
